version: "3.8"
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  flask:
    build:
      context: .
    container_name: "flask"
    depends_on:
      - "traefik"
      - "postgres"
    volumes:
      - "./webapp:/webapp/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.php-apache.loadbalancer.server.port=80"
      - "traefik.http.routers.php-apache.rule=Host(`lvh.me`, `pfp.lvh.me`, `example.com`)"
      - "traefik.http.routers.php-apache.entrypoints=web"

  postgres:
    image: "postgres:13"
    container_name: "postgres"
    depends_on:
      - "traefik"
    environment:
      POSTGRES_DB: "dbase"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpass"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      #- "./postgres_seed.sql:/docker-entrypoint-initdb.d/postgres_seed.sql"
      - "./db-data:/var/lib/postgresql/data"
    labels:
      - "traefik.enable=false"
  
  pgadmin:
    image: "dpage/pgadmin4:latest"
    container_name: "pgadmin"
    depends_on:
      - "traefik"
    environment:
      PGADMIN_DEFAULT_EMAIL: "dbuser@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "dbpass"
      PGADMIN_LISTEN_PORT: "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`pga.lvh.me`)"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  default:
    external:
      name: "traefikNetwork"
